### ISSUE TITLE
输入sudo pip3 install -r SatanSword.py 时报错

### ISSUE THREAD

**Issue by za0za0** [Lucifer1993/SatanSword#2]
ERROR: Invalid requirement: 'from gevent import monkey' (from line 5 of SatanSword.py)
Python版本为3.7.4，已经查阅网上相关报错解决方式，暂无法解决，是否因为Python版本过低造成？如何解决，求救

**Comment by Lucifer1993** [comment]
朋友，我正吃着饭差点没喷出来🤦‍♂️，pip3 install -r requirements.txt，你为啥要-r SatanSword.py呢？

**Comment by za0za0** [comment]
我是弟弟，我错了orz

**Comment by za0za0** [comment]
我是弟弟，我错了orz
