### ISSUE TITLE
缺少Python模块: gnureadline

### ISSUE THREAD

**Issue by bbkali** [Lucifer1993/SatanSword#5]
pip3 install gnureadline报错error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Beginning configuration for readline-8.0 for x86_64-pc-linux-gnu
    
    checking whether make sets $(MAKE)... yes
    checking for gcc... no
    checking for cc... no
    checking for cl.exe... no
    configure: error: in `/tmp/pip-install-pcxjwsss/gnureadline/rl/readline-lib':
    configure: error: no acceptable C compiler found in $PATH
    See `config.log' for more details
    
    ============ Building the readline extension module ============
    
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    copying readline.py -> build/lib.linux-x86_64-3.8
    running egg_info
    writing gnureadline.egg-info/PKG-INFO
    writing dependency_links to gnureadline.egg-info/dependency_links.txt
    writing top-level names to gnureadline.egg-info/top_level.txt
    reading manifest file 'gnureadline.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'readline*-0*' under directory 'rl'
    writing manifest file 'gnureadline.egg-info/SOURCES.txt'
    running build_ext
    building 'gnureadline' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/Modules
    creating build/temp.linux-x86_64-3.8/Modules/3.x
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DHAVE_RL_APPEND_HISTORY -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -DHAVE_RL_RESIZE_TERMINAL -I. -I/usr/include/python3.8 -c Modules/3.x/readline.c -o build/temp.linux-x86_64-3.8/Modules/3.x/readline.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pcxjwsss/gnureadline/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pcxjwsss/gnureadline/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wudwyris/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/gnureadline Check the logs for full command output.
root@bbkali:~/SatanSword# error: command 'x86_64-linux-gnu-gcc' failed with exit

**Comment by Lucifer1993** [comment]
apt install  libncurses5-dev

**Comment by bbkali** [comment]
已经安装了这个libncurses5-dev 已经是最新版 (6.2-1)。，是gnureadline 安装配置模块时无法正常配置发生错误.是libncurses5-dev版本问题么？
