### ISSUE TITLE
数据库已配置，执行命令均报错Nonetype

### ISSUE THREAD

**Issue by bbkali** [Lucifer1993/SatanSword#8]
SatanSword⚡=>>> status
EXCEPTION of type 'TypeError' occurred with message: ''NoneType' object is not subscriptable'
To enable full traceback, run the following command: 'set debug true'
SatanSword⚡=>>> search phpcms
EXCEPTION of type 'TypeError' occurred with message: ''NoneType' object is not iterable'
To enable full traceback, run the following command: 'set debug true'
SatanSword⚡=>>
![20200703011548](https://user-images.githubusercontent.com/25882066/86390659-0e265e80-bccb-11ea-9026-7984d8209371.png)

**Comment by Lucifer1993** [comment]
数据库没创建对吧

**Comment by bbkali** [comment]
在database.py中加上unix_socket='/var/run/mysqld/mysqld.sock'解决了，同时发现编码要改成utf8和utf8_general_ci才能正常调用数据库数据。看了下代码对历史信息搜集的结果无法查询和调用么？
